server:
  port: 8080

spring:
  redis:
#    host: 106.13.47.65
    host: 127.0.0.1
    password: redis
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 100
        max-wait: -1ms
        min-idle: 10
        max-idle: 20
    timeout: 1000m
  jackson:
    date-format: yyyy-MM-dd hh:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: zhanghang
    # url: jdbc:mysql://193.112.120.245:3306/micro-platform?characterEncoding=UTF-8&serverTimezone=GMT
    url: jdbc:mysql://127.0.0.1:3306/micro-platform?characterEncoding=UTF-8&serverTimezone=GMT
    dbcp2:
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      validation-query: select 'x'
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  thymeleaf:
    suffix: .html
    mode: HTML
    cache: false
    encoding: UTF-8
    check-template-location: true
    prefix: classpath:/templates/


mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.hang
  config-location: classpath:mybatis-config.xml

wx:
  appId: wxba259c9cc25c8a20
  appSecret: c911996088c1946f02d1af55d452a539

requiredHeaders: appPlatform,sessionId